---
title: "Rasch Analysis of the P3CEQ"
---

Install and load packages

```{r}
#install.packages(c("eRm", "tidyverse","pander", "checkpoint"))
require(eRm)
require(tidyverse)
require(pander)
require(checkpoint)
```

import and clean data

```{r import}
raw_data <- read.csv("C:/Users/bfosh/P3CEQ/tblIPC_LTC6.csv")

```


```{r clean}
# isolate items from data frame
items <- raw_data %>% select(Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8, Q8b, Q8c, Q8d,  Q9,  Q10, Q11)

#check data starts from 0
for(i in 1:ncol(items)){
  if(0%in%items[,i]==FALSE){
    items[, i] = items[,i] - 1
}}

#Rescore response 99 (don't know) to 0
items[items >= 98] <- 0

#rescore item 4 responses  to 3
items$Q4[items$Q4 >3] <- 3

# remove where only 1 item available
qs <- items
qs <- items %>% 
  mutate(nmiss=rowSums(is.na(.))) %>% 
  filter(nmiss < (ncol(qs)-1)) %>% 
  select(-nmiss) 

qs$q8new <- rowSums(qs[,c("Q8", "Q8b", "Q8c", "Q8d")], na.rm=TRUE) / 4

qs$q8new <- round(qs$q8new,0)
#qs$q8new <-sprintf("%.3f", qs$q8new)

write.csv(qs, "C:/Users/bfosh/P3CEQ/qs.csv")

```


#Perform Partial Credit Rasch Analysis


```{r pcm}

# Runs the Partial Credit Model
qs.no <- qs %>% select(Q1, Q2, Q3, Q5, Q6, Q9, Q10, Q11)
qs.no.clean <- qs.no %>% 
  mutate(nmiss=rowSums(is.na(.))) %>% 
  # remove where only 1 item available
  filter(nmiss < (ncol(qs.no)-1)) %>% 
  select(-nmiss) 
pcm.2 <- eRm::PCM(qs.no.clean)
```

ICC plots

```{r icc}
# get ICC plots
plotICC(pcm.2, mplot = F, legpos = "right", ask = FALSE)
```

PI Plots

```{r PI}
#get PI plots
pcm2.pp <- person.parameter(pcm.2)
plotPImap(pcm.2, sorted = TRUE, pp=pcm2.pp)
```



Model fit:
```{r fit}

pres.pcm <- person.parameter(pcm.2)
itemfit(pres.pcm)
itemfit
```


Extract item thresholds


```{r thresholds}
thresholds(pcm.2)
```


Summarising ICC plots with transition points

```{r ICC_summarise}
itemfit(pcm2.pp)
pmat.df <- pmat(pcm2.pp) %>% as_data_frame()
pmat.df.sums <- pmat.df %>% 
  summarise_all(funs(mean(., na.rm=T))) %>% 
  reshape2::melt() %>%
  separate(variable, c("q", "item"))

pmat.df.sums %>% 
  reshape2::dcast(q~item) %>% 
  pander
```




Identify where items add latent information

```{r latent_plot }
plotINFO(pcm.2, legpos = "right")
```


PLot PW map

```{r PWmap}
plotPWmap(pcm.2, imap=T)
```


Reliability parameters

```{r reliability}
# get reliability parameters
SepRel(pres.pcm)
```


```{r render}
rmarkdown::render("pcm.rmd", output_dir = "C:/Users/bfosh/P3CEQ/html")
```

